version: '3'
services:
  nacos:
    image: nacos/nacos-server:v2.0.4-slim
    container_name: cheeseim-nacos
    env_file:
      - ./env/nacos.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - "./conf/nacos.properties:/home/nacos/conf/application.properties"
  kafka:
    image: bitnami/kafka:2.8 
    container_name: cheeseim-kafka 
    env_file:
      - ./env/kafka.env
    ports:
      - "9092:9092"
        #    volumes:
        #      - ./data/kafka:/bitnami/kafka
    depends_on:
      - zookeeper
  kowl:
    image: quay.io/cloudhut/kowl:v1.5.0
    container_name: cheeseim-kowl
    hostname: kowl
    volumes:
      - ./conf/kowl.yml:/etc/kowl/config.yaml
    ports:
      - "9090:9090"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka
  zookeeper:
    image: bitnami/zookeeper:3.8 
    container_name: cheeseim-zk 
    env_file:
      - ./env/zookeeper.env
    ports:
      - "2181:2181"
        #    volumes:
        #      - ./conf/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
