version: '3'
services:
  nacos:
    image: nacos/nacos-server:v2.0.4-slim
    container_name: nacos
    env_file:
      - ./env/nacos.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - "./conf/nacos.properties:/home/nacos/conf/application.properties"