apply plugin: 'application'

bootJar {
    enabled = false
}

jar {
    enabled = true
}

application {
    mainClass = 'com.cheeseocean.im.client.cli.CliApplication'
}

dependencies {
    implementation project(':apps:im_java_client_demo:client-core')
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
