# Gradle?? - ???????
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.daemon=true

# ???? - ??????
org.gradle.internal.http.connectionTimeout=180000
org.gradle.internal.http.socketTimeout=180000
systemProp.http.keepAlive=true
systemProp.http.maxConnections=20

# ???? - ???????
org.gradle.unsafe.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn

# ????
version=1.0.0
group=com.cheeseocean.im

# ???? - ????
dubboVersion=3.2.8
kafkaVersion=3.7.0
springBootVersion=3.2.4
lombokVersion=1.18.32
junitVersion=5.10.2
nettyVersion=4.1.100.Final
jacksonVersion=2.17.0
slf4jVersion=2.0.12
logbackVersion=1.5.3
nacosVersion=2.3.2
