dependencies {
    implementation project(':common-core')
    implementation project(':common-api')
    implementation project(':config')
    implementation 'com.google.protobuf:protobuf-java:3.25.3'

    // 测试依赖
    testImplementation 'org.java-websocket:Java-WebSocket:1.5.6'
    testImplementation 'org.springframework.kafka:spring-kafka'
    testImplementation project(':postman')
    testImplementation project(':postbox')
    testImplementation project(':postmaster')
}
