dependencies {
    implementation project(':common-core')
    implementation project(':common-api')
    implementation project(':config')

    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.kafka:spring-kafka'

    // RPC框架 (Dubbo)
    implementation 'org.apache.dubbo:dubbo-spring-boot-starter'
    implementation 'org.apache.dubbo:dubbo-registry-nacos'

    // JSON处理
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.core:jackson-core'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // 工具类
    implementation 'org.apache.commons:commons-lang3:3.18.0'

    // 测试依赖
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    testImplementation 'org.java-websocket:Java-WebSocket:1.5.6'
    testImplementation 'org.springframework.kafka:spring-kafka'
    testImplementation project(':postman')
    testImplementation project(':postbox')
    testImplementation project(':push')
    testRuntimeOnly 'ch.qos.logback:logback-core:1.5.25'
}
