dependencies {
    implementation project(':common')
    implementation project(':config')
    implementation project(':authcenter')
    implementation project(':postoffice')
    implementation project(':postman')
    implementation project(':postbox')
    implementation project(':push')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.apache.dubbo:dubbo-spring-boot-starter'
}
