dependencies {
    implementation project(':common-core')
    implementation project(':infra-queue')
    implementation project(':storage-history')
    implementation project(':common-api')
    implementation project(':config')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.apache.dubbo:dubbo-spring-boot-starter'
    implementation 'com.google.protobuf:protobuf-java:3.25.3'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
}
