spring:
  config:
    import:
      - classpath:common.yml
      - classpath:module-postman.yml

app:
  runtime:
    mode: standalone

cheeseim:
  push:
    scheduled-tasks:
      enabled: true

dubbo:
  application:
    name: cheese-im-push
  registry:
    address: nacos://${nacos.server-addr:localhost:8848}
    register: true
    subscribe: true
  config-center:
    address: nacos://${nacos.server-addr:localhost:8848}
  metadata-report:
    address: nacos://${nacos.server-addr:localhost:8848}
  protocol:
    name: dubbo
    port: 20883
    injvm: false
  consumer:
    injvm: false
