spring:
  config:
    import:
      - classpath:common.yml
      - classpath:module-postbox.yml
      - classpath:application-cluster.yml

dubbo:
  application:
    name: cheese-im-postbox
  registry:
    address: nacos://${nacos.server-addr:localhost:8848}
    register: true
    subscribe: true
  config-center:
    address: nacos://${nacos.server-addr:localhost:8848}
  metadata-report:
    address: nacos://${nacos.server-addr:localhost:8848}
  protocol:
    name: dubbo
    port: 20882
    injvm: false
  consumer:
    injvm: false
