spring:
  config:
    import:
      - classpath:common.yml
      - classpath:module-authcenter.yml
      - classpath:module-business.yml
      - classpath:module-postoffice.yml
      - classpath:module-postman.yml
      - classpath:module-postbox.yml
      - classpath:module-postmaster.yml
  application:
    name: cheese-im-all-in-one
server:
  port: 18079

cheeseim:
  queue:
    type: chronicle
    data-dir: data/queue
  cache:
    data-dir: data/cache
  state:
    data-dir: data/state
    sequence-range-size: 100
  runtime:
    mode: all-in-one
  modules:
    authcenter:
      enabled: true
    social:
      enabled: true

dubbo:
  application:
    name: cheese-im-all-in-one
  registry:
    address: N/A
    register: false
    subscribe: false
  protocol:
    name: injvm
    port: -1
    injvm: true
  provider:
    protocol: injvm
  consumer:
    injvm: true
    check: false
