spring:
  config:
    import:
      - classpath:common.yml
      - classpath:module-user.yml

app:
  runtime:
    mode: standalone

dubbo:
  application:
    name: cheese-im-user
  registry:
    address: nacos://${nacos.server-addr:localhost:8848}
    register: true
    subscribe: true
  config-center:
    address: nacos://${nacos.server-addr:localhost:8848}
  metadata-report:
    address: nacos://${nacos.server-addr:localhost:8848}
  protocol:
    name: dubbo
    port: 20886
    injvm: false
  consumer:
    injvm: false
