spring:
  application:
    name: cheese-im-user
  data:
    mongodb:
      host: ${mongodb.host:localhost}
      port: ${mongodb.port:27017}
      database: ${mongodb.database:cheese_im}
    redis:
      database: 0

server:
  port: 18086

app:
  modules:
    user:
      enabled: true

logging:
  level:
    com.cheeseocean.im.user: INFO
