spring:
  application:
    name: cheese-im-postman
  data:
    redis:
      database: 1
  kafka:
    consumer:
      group-id: postman-delivery-group

cheeseim:
  message:
    revoke-window-seconds: ${CHEESEIM_MESSAGE_REVOKE_WINDOW_SECONDS:120}
  postman:

logging:
  level:
    com.cheeseocean.im.postman: INFO
    org.springframework.data.mongodb: WARN
