spring:
  application:
    name: cheese-im-postman
  data:
    redis:
      database: 1
  kafka:
    consumer:
      group-id: postman-delivery-group

cheeseim:
  postman:

logging:
  level:
    com.cheeseocean.im.postman: INFO
    org.springframework.data.mongodb: WARN