spring:
  application:
    name: cheese-im-authcenter

server:
  port: 18084

app:
  modules:
    authcenter:
      enabled: true

cheeseim:
  authcenter:
    security:
      jwtSecret: "CheeseIM2024Secret!CheeseIM2024Secret!"
      tokenExpiration: 86400000
    wsTicket:
      ttlMs: 60000
