spring:
  application:
    name: cheese-im-postman
  data:
    redis:
      database: 1
  kafka:
    consumer:
      group-id: postman-delivery-group

server:
  port: 18081

cheeseim:
  delivery:
    compensation:
      max-retries: 3
      retry-delay-seconds: 10

logging:
  level:
    com.cheeseocean.im.postman: INFO
    org.springframework.kafka: WARN
    org.springframework.data.mongodb: WARN
