dependencies {
    implementation project(':common-api')
    implementation project(':common-core')
    implementation project(':config')
    implementation project(':authcenter')
    implementation project(':business')
    implementation project(':postbox')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}
