dependencies {
    implementation project(':common-api')
    implementation project(':common-core')
    implementation project(':config')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.apache.dubbo:dubbo-spring-boot-starter'
}
