dependencies {
    implementation project(':common-api')
    implementation project(':common-core')
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}
