dependencies {
    implementation project(':common-core')
    implementation project(':common-api')
    implementation project(':config')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.apache.dubbo:dubbo-spring-boot-starter'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework:spring-tx'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
}
