// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: message_protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoMessageOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NeedHistory      *bool                  `protobuf:"varint,1,opt,name=need_history,json=needHistory,proto3,oneof" json:"need_history,omitempty"`
	NeedConversation *bool                  `protobuf:"varint,2,opt,name=need_conversation,json=needConversation,proto3,oneof" json:"need_conversation,omitempty"`
	NeedUnreadCount  *bool                  `protobuf:"varint,3,opt,name=need_unread_count,json=needUnreadCount,proto3,oneof" json:"need_unread_count,omitempty"`
	NeedOnlinePush   *bool                  `protobuf:"varint,4,opt,name=need_online_push,json=needOnlinePush,proto3,oneof" json:"need_online_push,omitempty"`
	NeedOfflinePush  *bool                  `protobuf:"varint,5,opt,name=need_offline_push,json=needOfflinePush,proto3,oneof" json:"need_offline_push,omitempty"`
	SenderSync       *bool                  `protobuf:"varint,6,opt,name=sender_sync,json=senderSync,proto3,oneof" json:"sender_sync,omitempty"`
	Notification     *bool                  `protobuf:"varint,7,opt,name=notification,proto3,oneof" json:"notification,omitempty"`
	NeedLastMessage  *bool                  `protobuf:"varint,8,opt,name=need_last_message,json=needLastMessage,proto3,oneof" json:"need_last_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoMessageOptions) Reset() {
	*x = ProtoMessageOptions{}
	mi := &file_message_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessageOptions) ProtoMessage() {}

func (x *ProtoMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessageOptions.ProtoReflect.Descriptor instead.
func (*ProtoMessageOptions) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMessageOptions) GetNeedHistory() bool {
	if x != nil && x.NeedHistory != nil {
		return *x.NeedHistory
	}
	return false
}

func (x *ProtoMessageOptions) GetNeedConversation() bool {
	if x != nil && x.NeedConversation != nil {
		return *x.NeedConversation
	}
	return false
}

func (x *ProtoMessageOptions) GetNeedUnreadCount() bool {
	if x != nil && x.NeedUnreadCount != nil {
		return *x.NeedUnreadCount
	}
	return false
}

func (x *ProtoMessageOptions) GetNeedOnlinePush() bool {
	if x != nil && x.NeedOnlinePush != nil {
		return *x.NeedOnlinePush
	}
	return false
}

func (x *ProtoMessageOptions) GetNeedOfflinePush() bool {
	if x != nil && x.NeedOfflinePush != nil {
		return *x.NeedOfflinePush
	}
	return false
}

func (x *ProtoMessageOptions) GetSenderSync() bool {
	if x != nil && x.SenderSync != nil {
		return *x.SenderSync
	}
	return false
}

func (x *ProtoMessageOptions) GetNotification() bool {
	if x != nil && x.Notification != nil {
		return *x.Notification
	}
	return false
}

func (x *ProtoMessageOptions) GetNeedLastMessage() bool {
	if x != nil && x.NeedLastMessage != nil {
		return *x.NeedLastMessage
	}
	return false
}

type ProtoOfflinePushInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Ex            string                 `protobuf:"bytes,3,opt,name=ex,proto3" json:"ex,omitempty"`
	IosPushSound  string                 `protobuf:"bytes,4,opt,name=ios_push_sound,json=iosPushSound,proto3" json:"ios_push_sound,omitempty"`
	IosBadgeCount *bool                  `protobuf:"varint,5,opt,name=ios_badge_count,json=iosBadgeCount,proto3,oneof" json:"ios_badge_count,omitempty"`
	SignalInfo    string                 `protobuf:"bytes,6,opt,name=signal_info,json=signalInfo,proto3" json:"signal_info,omitempty"`
	PushExtras    map[string]string      `protobuf:"bytes,7,rep,name=push_extras,json=pushExtras,proto3" json:"push_extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoOfflinePushInfo) Reset() {
	*x = ProtoOfflinePushInfo{}
	mi := &file_message_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoOfflinePushInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOfflinePushInfo) ProtoMessage() {}

func (x *ProtoOfflinePushInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOfflinePushInfo.ProtoReflect.Descriptor instead.
func (*ProtoOfflinePushInfo) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoOfflinePushInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProtoOfflinePushInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProtoOfflinePushInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *ProtoOfflinePushInfo) GetIosPushSound() string {
	if x != nil {
		return x.IosPushSound
	}
	return ""
}

func (x *ProtoOfflinePushInfo) GetIosBadgeCount() bool {
	if x != nil && x.IosBadgeCount != nil {
		return *x.IosBadgeCount
	}
	return false
}

func (x *ProtoOfflinePushInfo) GetSignalInfo() string {
	if x != nil {
		return x.SignalInfo
	}
	return ""
}

func (x *ProtoOfflinePushInfo) GetPushExtras() map[string]string {
	if x != nil {
		return x.PushExtras
	}
	return nil
}

type ProtoMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId     string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ServerMsgId     string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId      string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	GroupId         string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Content         []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ContentType     int32                  `protobuf:"varint,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ChatType        int32                  `protobuf:"varint,8,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	SendTime        int64                  `protobuf:"varint,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	CreateTime      int64                  `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Status          int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	PlatformCode    int32                  `protobuf:"varint,12,opt,name=platform_code,json=platformCode,proto3" json:"platform_code,omitempty"`
	Attributes      map[string]string      `protobuf:"bytes,13,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UniqueId        string                 `protobuf:"bytes,14,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Source          int32                  `protobuf:"varint,15,opt,name=source,proto3" json:"source,omitempty"`
	Options         *ProtoMessageOptions   `protobuf:"bytes,16,opt,name=options,proto3" json:"options,omitempty"`
	Seq             int64                  `protobuf:"varint,17,opt,name=seq,proto3" json:"seq,omitempty"`
	OfflinePushInfo *ProtoOfflinePushInfo  `protobuf:"bytes,18,opt,name=offline_push_info,json=offlinePushInfo,proto3" json:"offline_push_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_message_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *ProtoMessage) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *ProtoMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ProtoMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ProtoMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ProtoMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ProtoMessage) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *ProtoMessage) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *ProtoMessage) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ProtoMessage) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ProtoMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProtoMessage) GetPlatformCode() int32 {
	if x != nil {
		return x.PlatformCode
	}
	return 0
}

func (x *ProtoMessage) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ProtoMessage) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *ProtoMessage) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *ProtoMessage) GetOptions() *ProtoMessageOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ProtoMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProtoMessage) GetOfflinePushInfo() *ProtoOfflinePushInfo {
	if x != nil {
		return x.OfflinePushInfo
	}
	return nil
}

type ProtoHistoryEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastMaxSeq     int64                  `protobuf:"varint,2,opt,name=last_max_seq,json=lastMaxSeq,proto3" json:"last_max_seq,omitempty"`
	BeginSeq       int64                  `protobuf:"varint,3,opt,name=begin_seq,json=beginSeq,proto3" json:"begin_seq,omitempty"`
	EndSeq         int64                  `protobuf:"varint,4,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`
	Messages       []*ProtoMessage        `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtoHistoryEvent) Reset() {
	*x = ProtoHistoryEvent{}
	mi := &file_message_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoHistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHistoryEvent) ProtoMessage() {}

func (x *ProtoHistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHistoryEvent.ProtoReflect.Descriptor instead.
func (*ProtoHistoryEvent) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoHistoryEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProtoHistoryEvent) GetLastMaxSeq() int64 {
	if x != nil {
		return x.LastMaxSeq
	}
	return 0
}

func (x *ProtoHistoryEvent) GetBeginSeq() int64 {
	if x != nil {
		return x.BeginSeq
	}
	return 0
}

func (x *ProtoHistoryEvent) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *ProtoHistoryEvent) GetMessages() []*ProtoMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ProtoOfflinePushEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	ServerMsgId    string                 `protobuf:"bytes,4,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SessionType    int32                  `protobuf:"varint,6,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	ContentType    int32                  `protobuf:"varint,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Notification   bool                   `protobuf:"varint,8,opt,name=notification,proto3" json:"notification,omitempty"`
	Title          string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Attributes     map[string]string      `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtoOfflinePushEvent) Reset() {
	*x = ProtoOfflinePushEvent{}
	mi := &file_message_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoOfflinePushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOfflinePushEvent) ProtoMessage() {}

func (x *ProtoOfflinePushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOfflinePushEvent.ProtoReflect.Descriptor instead.
func (*ProtoOfflinePushEvent) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoOfflinePushEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProtoOfflinePushEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProtoOfflinePushEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProtoOfflinePushEvent) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *ProtoOfflinePushEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ProtoOfflinePushEvent) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *ProtoOfflinePushEvent) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *ProtoOfflinePushEvent) GetNotification() bool {
	if x != nil {
		return x.Notification
	}
	return false
}

func (x *ProtoOfflinePushEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProtoOfflinePushEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProtoOfflinePushEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ProtoAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoAuthRequest) Reset() {
	*x = ProtoAuthRequest{}
	mi := &file_message_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoAuthRequest) ProtoMessage() {}

func (x *ProtoAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoAuthRequest.ProtoReflect.Descriptor instead.
func (*ProtoAuthRequest) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoAuthRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type ProtoAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoAuthResponse) Reset() {
	*x = ProtoAuthResponse{}
	mi := &file_message_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoAuthResponse) ProtoMessage() {}

func (x *ProtoAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoAuthResponse.ProtoReflect.Descriptor instead.
func (*ProtoAuthResponse) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoAuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProtoAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProtoConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoConnectResponse) Reset() {
	*x = ProtoConnectResponse{}
	mi := &file_message_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoConnectResponse) ProtoMessage() {}

func (x *ProtoConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoConnectResponse.ProtoReflect.Descriptor instead.
func (*ProtoConnectResponse) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoConnectResponse) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ProtoConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProtoHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoHeartbeatResponse) Reset() {
	*x = ProtoHeartbeatResponse{}
	mi := &file_message_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoHeartbeatResponse) ProtoMessage() {}

func (x *ProtoHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ProtoHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoHeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProtoErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoErrorResponse) Reset() {
	*x = ProtoErrorResponse{}
	mi := &file_message_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoErrorResponse) ProtoMessage() {}

func (x *ProtoErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoErrorResponse.ProtoReflect.Descriptor instead.
func (*ProtoErrorResponse) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *ProtoErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProtoErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProtoChatSendAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId   string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	SendTime      int64                  `protobuf:"varint,3,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoChatSendAck) Reset() {
	*x = ProtoChatSendAck{}
	mi := &file_message_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoChatSendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoChatSendAck) ProtoMessage() {}

func (x *ProtoChatSendAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoChatSendAck.ProtoReflect.Descriptor instead.
func (*ProtoChatSendAck) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ProtoChatSendAck) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *ProtoChatSendAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *ProtoChatSendAck) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type ProtoChatReadCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,2,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	DeviceId       string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OpId           string                 `protobuf:"bytes,4,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtoChatReadCommand) Reset() {
	*x = ProtoChatReadCommand{}
	mi := &file_message_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoChatReadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoChatReadCommand) ProtoMessage() {}

func (x *ProtoChatReadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoChatReadCommand.ProtoReflect.Descriptor instead.
func (*ProtoChatReadCommand) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *ProtoChatReadCommand) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProtoChatReadCommand) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *ProtoChatReadCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ProtoChatReadCommand) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

type ProtoChatReadNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReaderId       string                 `protobuf:"bytes,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,3,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtoChatReadNotify) Reset() {
	*x = ProtoChatReadNotify{}
	mi := &file_message_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoChatReadNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoChatReadNotify) ProtoMessage() {}

func (x *ProtoChatReadNotify) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoChatReadNotify.ProtoReflect.Descriptor instead.
func (*ProtoChatReadNotify) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *ProtoChatReadNotify) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProtoChatReadNotify) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *ProtoChatReadNotify) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *ProtoChatReadNotify) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ProtoChatRevokeCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ServerMsgId    string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	OpId           string                 `protobuf:"bytes,3,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtoChatRevokeCommand) Reset() {
	*x = ProtoChatRevokeCommand{}
	mi := &file_message_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoChatRevokeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoChatRevokeCommand) ProtoMessage() {}

func (x *ProtoChatRevokeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoChatRevokeCommand.ProtoReflect.Descriptor instead.
func (*ProtoChatRevokeCommand) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *ProtoChatRevokeCommand) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProtoChatRevokeCommand) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *ProtoChatRevokeCommand) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *ProtoChatRevokeCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProtoChatRevokeNotify struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ServerMsgId      string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	OperatorUserId   string                 `protobuf:"bytes,3,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	OperatorName     string                 `protobuf:"bytes,4,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	TargetSenderId   string                 `protobuf:"bytes,5,opt,name=target_sender_id,json=targetSenderId,proto3" json:"target_sender_id,omitempty"`
	TargetSenderName string                 `protobuf:"bytes,6,opt,name=target_sender_name,json=targetSenderName,proto3" json:"target_sender_name,omitempty"`
	RevokedAt        int64                  `protobuf:"varint,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	MutationVersion  int64                  `protobuf:"varint,8,opt,name=mutation_version,json=mutationVersion,proto3" json:"mutation_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoChatRevokeNotify) Reset() {
	*x = ProtoChatRevokeNotify{}
	mi := &file_message_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoChatRevokeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoChatRevokeNotify) ProtoMessage() {}

func (x *ProtoChatRevokeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoChatRevokeNotify.ProtoReflect.Descriptor instead.
func (*ProtoChatRevokeNotify) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *ProtoChatRevokeNotify) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProtoChatRevokeNotify) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *ProtoChatRevokeNotify) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *ProtoChatRevokeNotify) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *ProtoChatRevokeNotify) GetTargetSenderId() string {
	if x != nil {
		return x.TargetSenderId
	}
	return ""
}

func (x *ProtoChatRevokeNotify) GetTargetSenderName() string {
	if x != nil {
		return x.TargetSenderName
	}
	return ""
}

func (x *ProtoChatRevokeNotify) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *ProtoChatRevokeNotify) GetMutationVersion() int64 {
	if x != nil {
		return x.MutationVersion
	}
	return 0
}

type ProtoForceLogoutNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoForceLogoutNotify) Reset() {
	*x = ProtoForceLogoutNotify{}
	mi := &file_message_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoForceLogoutNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoForceLogoutNotify) ProtoMessage() {}

func (x *ProtoForceLogoutNotify) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoForceLogoutNotify.ProtoReflect.Descriptor instead.
func (*ProtoForceLogoutNotify) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *ProtoForceLogoutNotify) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProtoForceLogoutNotify) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProtoForceLogoutNotify) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ProtoForceLogoutNotify) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

type ProtoClientEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Command   int32                  `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProtoClientEnvelope_Auth
	//	*ProtoClientEnvelope_ChatMessage
	//	*ProtoClientEnvelope_ChatRead
	//	*ProtoClientEnvelope_ChatRevoke
	Payload       isProtoClientEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoClientEnvelope) Reset() {
	*x = ProtoClientEnvelope{}
	mi := &file_message_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoClientEnvelope) ProtoMessage() {}

func (x *ProtoClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoClientEnvelope.ProtoReflect.Descriptor instead.
func (*ProtoClientEnvelope) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *ProtoClientEnvelope) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *ProtoClientEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProtoClientEnvelope) GetPayload() isProtoClientEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProtoClientEnvelope) GetAuth() *ProtoAuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*ProtoClientEnvelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ProtoClientEnvelope) GetChatMessage() *ProtoMessage {
	if x != nil {
		if x, ok := x.Payload.(*ProtoClientEnvelope_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *ProtoClientEnvelope) GetChatRead() *ProtoChatReadCommand {
	if x != nil {
		if x, ok := x.Payload.(*ProtoClientEnvelope_ChatRead); ok {
			return x.ChatRead
		}
	}
	return nil
}

func (x *ProtoClientEnvelope) GetChatRevoke() *ProtoChatRevokeCommand {
	if x != nil {
		if x, ok := x.Payload.(*ProtoClientEnvelope_ChatRevoke); ok {
			return x.ChatRevoke
		}
	}
	return nil
}

type isProtoClientEnvelope_Payload interface {
	isProtoClientEnvelope_Payload()
}

type ProtoClientEnvelope_Auth struct {
	Auth *ProtoAuthRequest `protobuf:"bytes,10,opt,name=auth,proto3,oneof"`
}

type ProtoClientEnvelope_ChatMessage struct {
	ChatMessage *ProtoMessage `protobuf:"bytes,11,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type ProtoClientEnvelope_ChatRead struct {
	ChatRead *ProtoChatReadCommand `protobuf:"bytes,12,opt,name=chat_read,json=chatRead,proto3,oneof"`
}

type ProtoClientEnvelope_ChatRevoke struct {
	ChatRevoke *ProtoChatRevokeCommand `protobuf:"bytes,13,opt,name=chat_revoke,json=chatRevoke,proto3,oneof"`
}

func (*ProtoClientEnvelope_Auth) isProtoClientEnvelope_Payload() {}

func (*ProtoClientEnvelope_ChatMessage) isProtoClientEnvelope_Payload() {}

func (*ProtoClientEnvelope_ChatRead) isProtoClientEnvelope_Payload() {}

func (*ProtoClientEnvelope_ChatRevoke) isProtoClientEnvelope_Payload() {}

type ProtoServerEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Command   int32                  `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProtoServerEnvelope_Connect
	//	*ProtoServerEnvelope_Auth
	//	*ProtoServerEnvelope_Heartbeat
	//	*ProtoServerEnvelope_ChatSendAck
	//	*ProtoServerEnvelope_ChatMessage
	//	*ProtoServerEnvelope_Error
	//	*ProtoServerEnvelope_ChatReadNotify
	//	*ProtoServerEnvelope_ChatRevokeNotify
	//	*ProtoServerEnvelope_ForceLogout
	Payload       isProtoServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoServerEnvelope) Reset() {
	*x = ProtoServerEnvelope{}
	mi := &file_message_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoServerEnvelope) ProtoMessage() {}

func (x *ProtoServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoServerEnvelope.ProtoReflect.Descriptor instead.
func (*ProtoServerEnvelope) Descriptor() ([]byte, []int) {
	return file_message_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *ProtoServerEnvelope) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *ProtoServerEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProtoServerEnvelope) GetPayload() isProtoServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProtoServerEnvelope) GetConnect() *ProtoConnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetAuth() *ProtoAuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetHeartbeat() *ProtoHeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetChatSendAck() *ProtoChatSendAck {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_ChatSendAck); ok {
			return x.ChatSendAck
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetChatMessage() *ProtoMessage {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetError() *ProtoErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetChatReadNotify() *ProtoChatReadNotify {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_ChatReadNotify); ok {
			return x.ChatReadNotify
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetChatRevokeNotify() *ProtoChatRevokeNotify {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_ChatRevokeNotify); ok {
			return x.ChatRevokeNotify
		}
	}
	return nil
}

func (x *ProtoServerEnvelope) GetForceLogout() *ProtoForceLogoutNotify {
	if x != nil {
		if x, ok := x.Payload.(*ProtoServerEnvelope_ForceLogout); ok {
			return x.ForceLogout
		}
	}
	return nil
}

type isProtoServerEnvelope_Payload interface {
	isProtoServerEnvelope_Payload()
}

type ProtoServerEnvelope_Connect struct {
	Connect *ProtoConnectResponse `protobuf:"bytes,9,opt,name=connect,proto3,oneof"`
}

type ProtoServerEnvelope_Auth struct {
	Auth *ProtoAuthResponse `protobuf:"bytes,10,opt,name=auth,proto3,oneof"`
}

type ProtoServerEnvelope_Heartbeat struct {
	Heartbeat *ProtoHeartbeatResponse `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type ProtoServerEnvelope_ChatSendAck struct {
	ChatSendAck *ProtoChatSendAck `protobuf:"bytes,12,opt,name=chat_send_ack,json=chatSendAck,proto3,oneof"`
}

type ProtoServerEnvelope_ChatMessage struct {
	ChatMessage *ProtoMessage `protobuf:"bytes,13,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type ProtoServerEnvelope_Error struct {
	Error *ProtoErrorResponse `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

type ProtoServerEnvelope_ChatReadNotify struct {
	ChatReadNotify *ProtoChatReadNotify `protobuf:"bytes,15,opt,name=chat_read_notify,json=chatReadNotify,proto3,oneof"`
}

type ProtoServerEnvelope_ChatRevokeNotify struct {
	ChatRevokeNotify *ProtoChatRevokeNotify `protobuf:"bytes,16,opt,name=chat_revoke_notify,json=chatRevokeNotify,proto3,oneof"`
}

type ProtoServerEnvelope_ForceLogout struct {
	ForceLogout *ProtoForceLogoutNotify `protobuf:"bytes,17,opt,name=force_logout,json=forceLogout,proto3,oneof"`
}

func (*ProtoServerEnvelope_Connect) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_Auth) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_Heartbeat) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_ChatSendAck) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_ChatMessage) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_Error) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_ChatReadNotify) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_ChatRevokeNotify) isProtoServerEnvelope_Payload() {}

func (*ProtoServerEnvelope_ForceLogout) isProtoServerEnvelope_Payload() {}

var File_message_protocol_proto protoreflect.FileDescriptor

const file_message_protocol_proto_rawDesc = "" +
	"\n" +
	"\x16message_protocol.proto\x12\x11cheeseim.protocol\"\x9f\x04\n" +
	"\x13ProtoMessageOptions\x12&\n" +
	"\fneed_history\x18\x01 \x01(\bH\x00R\vneedHistory\x88\x01\x01\x120\n" +
	"\x11need_conversation\x18\x02 \x01(\bH\x01R\x10needConversation\x88\x01\x01\x12/\n" +
	"\x11need_unread_count\x18\x03 \x01(\bH\x02R\x0fneedUnreadCount\x88\x01\x01\x12-\n" +
	"\x10need_online_push\x18\x04 \x01(\bH\x03R\x0eneedOnlinePush\x88\x01\x01\x12/\n" +
	"\x11need_offline_push\x18\x05 \x01(\bH\x04R\x0fneedOfflinePush\x88\x01\x01\x12$\n" +
	"\vsender_sync\x18\x06 \x01(\bH\x05R\n" +
	"senderSync\x88\x01\x01\x12'\n" +
	"\fnotification\x18\a \x01(\bH\x06R\fnotification\x88\x01\x01\x12/\n" +
	"\x11need_last_message\x18\b \x01(\bH\aR\x0fneedLastMessage\x88\x01\x01B\x0f\n" +
	"\r_need_historyB\x14\n" +
	"\x12_need_conversationB\x14\n" +
	"\x12_need_unread_countB\x13\n" +
	"\x11_need_online_pushB\x14\n" +
	"\x12_need_offline_pushB\x0e\n" +
	"\f_sender_syncB\x0f\n" +
	"\r_notificationB\x14\n" +
	"\x12_need_last_message\"\xf1\x02\n" +
	"\x14ProtoOfflinePushInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x0e\n" +
	"\x02ex\x18\x03 \x01(\tR\x02ex\x12$\n" +
	"\x0eios_push_sound\x18\x04 \x01(\tR\fiosPushSound\x12+\n" +
	"\x0fios_badge_count\x18\x05 \x01(\bH\x00R\riosBadgeCount\x88\x01\x01\x12\x1f\n" +
	"\vsignal_info\x18\x06 \x01(\tR\n" +
	"signalInfo\x12X\n" +
	"\vpush_extras\x18\a \x03(\v27.cheeseim.protocol.ProtoOfflinePushInfo.PushExtrasEntryR\n" +
	"pushExtras\x1a=\n" +
	"\x0fPushExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_ios_badge_count\"\xf2\x05\n" +
	"\fProtoMessage\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\"\n" +
	"\rserver_msg_id\x18\x02 \x01(\tR\vserverMsgId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\a \x01(\x05R\vcontentType\x12\x1b\n" +
	"\tchat_type\x18\b \x01(\x05R\bchatType\x12\x1b\n" +
	"\tsend_time\x18\t \x01(\x03R\bsendTime\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\x03R\n" +
	"createTime\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12#\n" +
	"\rplatform_code\x18\f \x01(\x05R\fplatformCode\x12O\n" +
	"\n" +
	"attributes\x18\r \x03(\v2/.cheeseim.protocol.ProtoMessage.AttributesEntryR\n" +
	"attributes\x12\x1b\n" +
	"\tunique_id\x18\x0e \x01(\tR\buniqueId\x12\x16\n" +
	"\x06source\x18\x0f \x01(\x05R\x06source\x12@\n" +
	"\aoptions\x18\x10 \x01(\v2&.cheeseim.protocol.ProtoMessageOptionsR\aoptions\x12\x10\n" +
	"\x03seq\x18\x11 \x01(\x03R\x03seq\x12S\n" +
	"\x11offline_push_info\x18\x12 \x01(\v2'.cheeseim.protocol.ProtoOfflinePushInfoR\x0fofflinePushInfo\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x11ProtoHistoryEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12 \n" +
	"\flast_max_seq\x18\x02 \x01(\x03R\n" +
	"lastMaxSeq\x12\x1b\n" +
	"\tbegin_seq\x18\x03 \x01(\x03R\bbeginSeq\x12\x17\n" +
	"\aend_seq\x18\x04 \x01(\x03R\x06endSeq\x12;\n" +
	"\bmessages\x18\x05 \x03(\v2\x1f.cheeseim.protocol.ProtoMessageR\bmessages\"\xdf\x03\n" +
	"\x15ProtoOfflinePushEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\"\n" +
	"\rserver_msg_id\x18\x04 \x01(\tR\vserverMsgId\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12!\n" +
	"\fsession_type\x18\x06 \x01(\x05R\vsessionType\x12!\n" +
	"\fcontent_type\x18\a \x01(\x05R\vcontentType\x12\"\n" +
	"\fnotification\x18\b \x01(\bR\fnotification\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12X\n" +
	"\n" +
	"attributes\x18\v \x03(\v28.cheeseim.protocol.ProtoOfflinePushEvent.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x10ProtoAuthRequest\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\"F\n" +
	"\x11ProtoAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x14ProtoConnectResponse\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x16ProtoHeartbeatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\x12ProtoErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x10ProtoChatSendAck\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12\x1b\n" +
	"\tsend_time\x18\x03 \x01(\x03R\bsendTime\"\x8c\x01\n" +
	"\x14ProtoChatReadCommand\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bread_seq\x18\x02 \x01(\x03R\areadSeq\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x13\n" +
	"\x05op_id\x18\x04 \x01(\tR\x04opId\"\x95\x01\n" +
	"\x13ProtoChatReadNotify\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\treader_id\x18\x02 \x01(\tR\breaderId\x12\x19\n" +
	"\bread_seq\x18\x03 \x01(\x03R\areadSeq\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"\x92\x01\n" +
	"\x16ProtoChatRevokeCommand\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rserver_msg_id\x18\x02 \x01(\tR\vserverMsgId\x12\x13\n" +
	"\x05op_id\x18\x03 \x01(\tR\x04opId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xd5\x02\n" +
	"\x15ProtoChatRevokeNotify\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rserver_msg_id\x18\x02 \x01(\tR\vserverMsgId\x12(\n" +
	"\x10operator_user_id\x18\x03 \x01(\tR\x0eoperatorUserId\x12#\n" +
	"\roperator_name\x18\x04 \x01(\tR\foperatorName\x12(\n" +
	"\x10target_sender_id\x18\x05 \x01(\tR\x0etargetSenderId\x12,\n" +
	"\x12target_sender_name\x18\x06 \x01(\tR\x10targetSenderName\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\a \x01(\x03R\trevokedAt\x12)\n" +
	"\x10mutation_version\x18\b \x01(\x03R\x0fmutationVersion\"\x8d\x01\n" +
	"\x16ProtoForceLogoutNotify\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\x03R\n" +
	"occurredAt\"\xf0\x02\n" +
	"\x13ProtoClientEnvelope\x12\x18\n" +
	"\acommand\x18\x01 \x01(\x05R\acommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x129\n" +
	"\x04auth\x18\n" +
	" \x01(\v2#.cheeseim.protocol.ProtoAuthRequestH\x00R\x04auth\x12D\n" +
	"\fchat_message\x18\v \x01(\v2\x1f.cheeseim.protocol.ProtoMessageH\x00R\vchatMessage\x12F\n" +
	"\tchat_read\x18\f \x01(\v2'.cheeseim.protocol.ProtoChatReadCommandH\x00R\bchatRead\x12L\n" +
	"\vchat_revoke\x18\r \x01(\v2).cheeseim.protocol.ProtoChatRevokeCommandH\x00R\n" +
	"chatRevokeB\t\n" +
	"\apayload\"\xf3\x05\n" +
	"\x13ProtoServerEnvelope\x12\x18\n" +
	"\acommand\x18\x01 \x01(\x05R\acommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12C\n" +
	"\aconnect\x18\t \x01(\v2'.cheeseim.protocol.ProtoConnectResponseH\x00R\aconnect\x12:\n" +
	"\x04auth\x18\n" +
	" \x01(\v2$.cheeseim.protocol.ProtoAuthResponseH\x00R\x04auth\x12I\n" +
	"\theartbeat\x18\v \x01(\v2).cheeseim.protocol.ProtoHeartbeatResponseH\x00R\theartbeat\x12I\n" +
	"\rchat_send_ack\x18\f \x01(\v2#.cheeseim.protocol.ProtoChatSendAckH\x00R\vchatSendAck\x12D\n" +
	"\fchat_message\x18\r \x01(\v2\x1f.cheeseim.protocol.ProtoMessageH\x00R\vchatMessage\x12=\n" +
	"\x05error\x18\x0e \x01(\v2%.cheeseim.protocol.ProtoErrorResponseH\x00R\x05error\x12R\n" +
	"\x10chat_read_notify\x18\x0f \x01(\v2&.cheeseim.protocol.ProtoChatReadNotifyH\x00R\x0echatReadNotify\x12X\n" +
	"\x12chat_revoke_notify\x18\x10 \x01(\v2(.cheeseim.protocol.ProtoChatRevokeNotifyH\x00R\x10chatRevokeNotify\x12N\n" +
	"\fforce_logout\x18\x11 \x01(\v2).cheeseim.protocol.ProtoForceLogoutNotifyH\x00R\vforceLogoutB\t\n" +
	"\apayloadB1Z/github.com/cheeseim/cheeseim-go-sdk/proto;protob\x06proto3"

var (
	file_message_protocol_proto_rawDescOnce sync.Once
	file_message_protocol_proto_rawDescData []byte
)

func file_message_protocol_proto_rawDescGZIP() []byte {
	file_message_protocol_proto_rawDescOnce.Do(func() {
		file_message_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_protocol_proto_rawDesc), len(file_message_protocol_proto_rawDesc)))
	})
	return file_message_protocol_proto_rawDescData
}

var file_message_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_message_protocol_proto_goTypes = []any{
	(*ProtoMessageOptions)(nil),    // 0: cheeseim.protocol.ProtoMessageOptions
	(*ProtoOfflinePushInfo)(nil),   // 1: cheeseim.protocol.ProtoOfflinePushInfo
	(*ProtoMessage)(nil),           // 2: cheeseim.protocol.ProtoMessage
	(*ProtoHistoryEvent)(nil),      // 3: cheeseim.protocol.ProtoHistoryEvent
	(*ProtoOfflinePushEvent)(nil),  // 4: cheeseim.protocol.ProtoOfflinePushEvent
	(*ProtoAuthRequest)(nil),       // 5: cheeseim.protocol.ProtoAuthRequest
	(*ProtoAuthResponse)(nil),      // 6: cheeseim.protocol.ProtoAuthResponse
	(*ProtoConnectResponse)(nil),   // 7: cheeseim.protocol.ProtoConnectResponse
	(*ProtoHeartbeatResponse)(nil), // 8: cheeseim.protocol.ProtoHeartbeatResponse
	(*ProtoErrorResponse)(nil),     // 9: cheeseim.protocol.ProtoErrorResponse
	(*ProtoChatSendAck)(nil),       // 10: cheeseim.protocol.ProtoChatSendAck
	(*ProtoChatReadCommand)(nil),   // 11: cheeseim.protocol.ProtoChatReadCommand
	(*ProtoChatReadNotify)(nil),    // 12: cheeseim.protocol.ProtoChatReadNotify
	(*ProtoChatRevokeCommand)(nil), // 13: cheeseim.protocol.ProtoChatRevokeCommand
	(*ProtoChatRevokeNotify)(nil),  // 14: cheeseim.protocol.ProtoChatRevokeNotify
	(*ProtoForceLogoutNotify)(nil), // 15: cheeseim.protocol.ProtoForceLogoutNotify
	(*ProtoClientEnvelope)(nil),    // 16: cheeseim.protocol.ProtoClientEnvelope
	(*ProtoServerEnvelope)(nil),    // 17: cheeseim.protocol.ProtoServerEnvelope
	nil,                            // 18: cheeseim.protocol.ProtoOfflinePushInfo.PushExtrasEntry
	nil,                            // 19: cheeseim.protocol.ProtoMessage.AttributesEntry
	nil,                            // 20: cheeseim.protocol.ProtoOfflinePushEvent.AttributesEntry
}
var file_message_protocol_proto_depIdxs = []int32{
	18, // 0: cheeseim.protocol.ProtoOfflinePushInfo.push_extras:type_name -> cheeseim.protocol.ProtoOfflinePushInfo.PushExtrasEntry
	19, // 1: cheeseim.protocol.ProtoMessage.attributes:type_name -> cheeseim.protocol.ProtoMessage.AttributesEntry
	0,  // 2: cheeseim.protocol.ProtoMessage.options:type_name -> cheeseim.protocol.ProtoMessageOptions
	1,  // 3: cheeseim.protocol.ProtoMessage.offline_push_info:type_name -> cheeseim.protocol.ProtoOfflinePushInfo
	2,  // 4: cheeseim.protocol.ProtoHistoryEvent.messages:type_name -> cheeseim.protocol.ProtoMessage
	20, // 5: cheeseim.protocol.ProtoOfflinePushEvent.attributes:type_name -> cheeseim.protocol.ProtoOfflinePushEvent.AttributesEntry
	5,  // 6: cheeseim.protocol.ProtoClientEnvelope.auth:type_name -> cheeseim.protocol.ProtoAuthRequest
	2,  // 7: cheeseim.protocol.ProtoClientEnvelope.chat_message:type_name -> cheeseim.protocol.ProtoMessage
	11, // 8: cheeseim.protocol.ProtoClientEnvelope.chat_read:type_name -> cheeseim.protocol.ProtoChatReadCommand
	13, // 9: cheeseim.protocol.ProtoClientEnvelope.chat_revoke:type_name -> cheeseim.protocol.ProtoChatRevokeCommand
	7,  // 10: cheeseim.protocol.ProtoServerEnvelope.connect:type_name -> cheeseim.protocol.ProtoConnectResponse
	6,  // 11: cheeseim.protocol.ProtoServerEnvelope.auth:type_name -> cheeseim.protocol.ProtoAuthResponse
	8,  // 12: cheeseim.protocol.ProtoServerEnvelope.heartbeat:type_name -> cheeseim.protocol.ProtoHeartbeatResponse
	10, // 13: cheeseim.protocol.ProtoServerEnvelope.chat_send_ack:type_name -> cheeseim.protocol.ProtoChatSendAck
	2,  // 14: cheeseim.protocol.ProtoServerEnvelope.chat_message:type_name -> cheeseim.protocol.ProtoMessage
	9,  // 15: cheeseim.protocol.ProtoServerEnvelope.error:type_name -> cheeseim.protocol.ProtoErrorResponse
	12, // 16: cheeseim.protocol.ProtoServerEnvelope.chat_read_notify:type_name -> cheeseim.protocol.ProtoChatReadNotify
	14, // 17: cheeseim.protocol.ProtoServerEnvelope.chat_revoke_notify:type_name -> cheeseim.protocol.ProtoChatRevokeNotify
	15, // 18: cheeseim.protocol.ProtoServerEnvelope.force_logout:type_name -> cheeseim.protocol.ProtoForceLogoutNotify
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_message_protocol_proto_init() }
func file_message_protocol_proto_init() {
	if File_message_protocol_proto != nil {
		return
	}
	file_message_protocol_proto_msgTypes[0].OneofWrappers = []any{}
	file_message_protocol_proto_msgTypes[1].OneofWrappers = []any{}
	file_message_protocol_proto_msgTypes[16].OneofWrappers = []any{
		(*ProtoClientEnvelope_Auth)(nil),
		(*ProtoClientEnvelope_ChatMessage)(nil),
		(*ProtoClientEnvelope_ChatRead)(nil),
		(*ProtoClientEnvelope_ChatRevoke)(nil),
	}
	file_message_protocol_proto_msgTypes[17].OneofWrappers = []any{
		(*ProtoServerEnvelope_Connect)(nil),
		(*ProtoServerEnvelope_Auth)(nil),
		(*ProtoServerEnvelope_Heartbeat)(nil),
		(*ProtoServerEnvelope_ChatSendAck)(nil),
		(*ProtoServerEnvelope_ChatMessage)(nil),
		(*ProtoServerEnvelope_Error)(nil),
		(*ProtoServerEnvelope_ChatReadNotify)(nil),
		(*ProtoServerEnvelope_ChatRevokeNotify)(nil),
		(*ProtoServerEnvelope_ForceLogout)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_protocol_proto_rawDesc), len(file_message_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_protocol_proto_goTypes,
		DependencyIndexes: file_message_protocol_proto_depIdxs,
		MessageInfos:      file_message_protocol_proto_msgTypes,
	}.Build()
	File_message_protocol_proto = out.File
	file_message_protocol_proto_goTypes = nil
	file_message_protocol_proto_depIdxs = nil
}
